# Generated by Django 4.0.1 on 2022-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startup_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
