# Generated by Django 4.0.1 on 2022-01-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hymnbookapp', '0002_alter_profile_startup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startup_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hymnbookapp.approved_sector'),
        ),
    ]
