# Generated by Django 4.0.1 on 2022-01-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnbookapp', '0003_alter_profile_startup_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
    ]
