# Generated by Django 4.0.1 on 2022-02-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnbookapp', '0005_profession_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
